name: Docker Build Verification

on:
  push:
    branches: [ main ]

jobs:
  verify-docker-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code with full history 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Build Docker image from custom path
    - name: Build Docker image
      run: | 
        docker build \
        -t app:build-${{ github.sha }} \
        -f docker/Dockerfile \
        docker/

        echo "Docker image built successfully"
        docker images | grep app
