name: Deployment script

on:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code with full history 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Build Docker image from custom path
    - name: Build Docker image
      run: | 
        docker build \
        -t app:build-${{ github.sha }} \
        -f docker/Dockerfile \
        docker/

        echo "Docker image built successfully"
        docker images | grep app 

  test:
    runs-on: ubuntu-latest
    needs: verify
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s

    steps:
      - uses: actions/checkout@v4
      
      - name: Build app image
        run: docker build -t app docker/
      
      - name: Run tests
        run: |
          docker run --network host \
            -e TESTING=1 \
            app pytest -v ./tests/

      - name: Push to docker registry
        if: success()
        run: |
          echo "Uncomment these lines after setting up registry secrets:"
            # docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            # docker push app:${{ github.sha }}
            # docker push app:latest
          echo "Would have pushed app:${{ github.sha }}"
      
     
          















    
